### ISSUE TITLE
Language selector on groonga.org is broken

### ISSUE THREAD

**Issue by kou** [groonga/groonga#1397]
URL: https://groonga.org/docs/

Select "日本語" from the dropdown at the top right.
You will move to https://groonga.org/docs/None not https://groonga.org/ja/docs/ .

`pydata_sphinx_theme` may change API.

**Comment by HashidaTKS** [comment]
This may because I have built docs with old `pydata_sphinx_thema` and latest `Sphinx` on https://github.com/groonga/groonga.org/commit/717d4f29d9deac2c3fb7c2568ca2c3de257c7bc7. (Sorry...)
Using latest `pydata_sphinx_thema` and `Sphinx` will solve this issue but it requires some changes on `conf.py`.

**Comment by HashidaTKS** [comment]
TODO: Using latest `pydata_sphinx_theme` and `Sphinx`, displaying the dark/light theme switcher.

**Comment by komainu8** [comment]
We resolved this issues at 92d498d2044215ca1faf2c967b574995dc5ca718.
