### ISSUE TITLE
doc: groonga create table for memcached automatically.

### ISSUE THREAD

**Issue by hiroyuki-sato** [groonga/groonga#453]
[Reference](http://blog.shigepon.info/blog/2016/01/15/use-groonga-for-django-cache/) (Japanese)

http://groonga.org/ja/docs/server/memcached.html

It is better to write following description.

Example.

You don't need to create table.
When groonga receive request, it create table automatically.
The table name is ``Memcache``.

Could you tell me how to update English doucment?
Should I change xxx.po file directory?

Best regards.

**Comment by kou** [comment]
> Could you tell me how to update English doucment?

@kenhys Could you describe about it?

**Comment by kenhys** [comment]
> Could you tell me how to update English doucment?
> Should I change xxx.po file directory?

Here is the document how to contribute 
http://groonga.org/ja/docs/contribution/documentation/introduction.html

To update English document, modify existent doc/source/*.rst is good enough
because po files for English document is automatically re-generated. (no need to edit doc/locale/en/LC_MESSAGES/*.po)

If you want to do more (translate document), see next i18n document here:
http://groonga.org/ja/docs/contribution/documentation/i18n.html

I hope it may help.

**Comment by kenhys** [comment]
Sorry, I've closed by mistake.

**Comment by hiroyuki-sato** [comment]
Thanks!!
